### ISSUE TITLE
Problem loading ur plugin 1.8.9

### ISSUE THREAD

**Issue by Benntehboss** [novucs/factions-top#133] opened 2020-04-06 10:19 UTC
[11:57:18] [Server thread/INFO]: [Factions] Enabling Factions v2.8.5
[11:57:18] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.5[0;36;22m] [0;33;1m=== ENABLE START ===[m
[11:57:19] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.8.5[0;36;22m] [0;33;1m=== ENABLE [0;32;1mCOMPLETE [0;33;1m(Took [0;35;1m699ms[0;33;1m) ===[m
[11:57:19] [Server thread/INFO]: [FactionsTop] Enabling FactionsTop v1.2.0
[11:57:19] [Server thread/INFO]: [FactionsTop] Essentials found, using as economy backend.
[11:57:19] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at net.novucs.ftop.shade.com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:50) ~[?:?]
	at net.novucs.ftop.Settings.loadHikariConfig(Settings.java:442) ~[?:?]
	at net.novucs.ftop.Settings.load(Settings.java:523) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:367) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:138) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot18.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	... 16 more
[11:57:19] [Server thread/INFO]: [GenBucket] Enabling GenBucket v1.0.7

**Comment by Phoenix616** [comment] 2020-04-06 18:33
You are not using the latest version, please update to the latest [build](https://ci.minebench.de/job/FactionsTop/) and see if the error persists.

**Comment by promlgxd** [comment] 2020-04-08 16:48
> You are not using the latest version, please update to the latest [build](https://ci.minebench.de/job/FactionsTop/) and see if the error persists.

I have updated and I have the same problem
[FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT
[18:43:07 INFO]: [FactionsTop] Essentials found, using as economy backend.
[18:43:07 ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at net.novucs.ftop.shade.com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:50) ~[?:?]
        at net.novucs.ftop.Settings.loadHikariConfig(Settings.java:442) ~[?:?]
        at net.novucs.ftop.Settings.load(Settings.java:523) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:385) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 16 more

in my case im using minecraft 1.12.2

**Comment by Benntehboss** [comment] 2020-04-09 20:27
Stille not working new error below

Factions2.8.5
Massivecore2.8.5

[22:19:58] [Server thread/INFO]: [FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT
[22:19:58] [Server thread/INFO]: [FactionsTop] Essentials found, using as economy backend.
[22:19:58] [Server thread/INFO]: [FactionsTop] Configuration file has been successfully updated.
[22:19:58] [Server thread/INFO]: [FactionsTop] H2 forcefully loaded, a reboot may be required.
[22:19:58] [Server thread/WARN]: HikariPool-1 - maxLifetime is less than 30000ms, setting to default 1800000ms.
[22:19:58] [Server thread/WARN]: HikariPool-1 - idleTimeout is less than 10000ms, setting to default 600000ms.
[22:19:58] [Server thread/INFO]: HikariPool-1 - Started.
[22:19:58] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:h2:./plugins/FactionsTop/database
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:298) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:91) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
	at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:24) ~[?:?]
	at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:19) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadDatabase(FactionsTopPlugin.java:193) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:140) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(DriverManager.java:315) ~[?:1.8.0_60]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81) ~[?:?]
	... 19 more
[22:19:58] [Server thread/INFO]: [FactionsTop] Disabling FactionsTop v1.2.1-SNAPSHOT
[22:19:58] [Server thread/INFO]: [FactionsTop] Preparing shutdown...
[22:19:58] [Server thread/INFO]: [FactionsTop] Shutting down chunk worth task...
[22:19:58] [Server thread/INFO]: [FactionsTop] Saving everything to database...
[22:19:58] [Server thread/INFO]: [FactionsTop] Terminating plugin services...
[22:19:58] [Server thread/ERROR]: Error occurred while disabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:178) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by Phoenix616** [comment] 2020-04-10 02:10
Sounds like the original issue is fixed now? Seems like your new issue is the same as #134.

**Closed by Phoenix616** 2020-04-10 02:10 UTC
