### ISSUE TITLE
Error with EpicSpawners v5.2.0.6

### ISSUE THREAD

**Issue by sandor111** [novucs/factions-top#95] opened 2018-07-27 20:03 UTC
Using paper 1.8.8 and EpicSpawners V5.2.0.6
and I'm getting this error on startup:
`[21:41:43] [Server thread/INFO]: [FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT
[21:41:43] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/songoda/epicspawners/EpicSpawners
	at net.novucs.ftop.hook.EpicSpawnersHook.initialize(EpicSpawnersHook.java:30) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadSpawnerStackerHook(FactionsTopPlugin.java:286) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.songoda.epicspawners.EpicSpawners
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 14 more`

**Comment by Phoenix616** [comment] 2018-07-28 21:56
Duplicate of #88

**Closed by Phoenix616** 2018-07-28 21:57 UTC
Labels: duplicate
