### ISSUE TITLE
Error with EpicSpawners 5.2.0.6 Legacy 1.12.jar

### ISSUE THREAD

**Issue by Smadger1** [novucs/factions-top#96] opened 2018-07-28 21:51 UTC
INFO [FactionsTop] Enabling FactionsTop v1.2.0
28.07 22:49:12 [Server] ERROR Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
28.07 22:49:12 [Server] INFO java.lang.NoClassDefFoundError: com/songoda/epicspawners/EpicSpawners
28.07 22:49:12 [Server] INFO at net.novucs.ftop.hook.EpicSpawnersHook.initialize(EpicSpawnersHook.java:30) ~[FactionsTop%20(4).jar:?]
28.07 22:49:12 [Server] INFO at net.novucs.ftop.FactionsTopPlugin.loadSpawnerStackerHook(FactionsTopPlugin.java:285) ~[FactionsTop%20(4).jar:?]
28.07 22:49:12 [Server] INFO at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:130) ~[FactionsTop%20(4).jar:?]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:313) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:272) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
28.07 22:49:12 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.songoda.epicspawners.EpicSpawners
28.07 22:49:12 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_161]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
28.07 22:49:12 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
28.07 22:49:12 [Server] INFO ... 14 more
28.07 22:49:12 [Server] INFO [FactionsTop] Disabling FactionsTop v1.2.0
28.07 22:49:12 [Server] INFO [FactionsTop] Preparing shutdown...
28.07 22:49:12 [Server] INFO [FactionsTop] Shutting down chunk worth task...
28.07 22:49:12 [Server] INFO [FactionsTop] Saving everything to database...
28.07 22:49:12 [Server] INFO [FactionsTop] Terminating plugin services...
28.07 22:49:12 [Server] ERROR Error occurred while disabling FactionsTop v1.2.0 (Is it up to date?)
28.07 22:49:12 [Server] INFO java.lang.NullPointerException
28.07 22:49:12 [Server] INFO at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:177) ~[FactionsTop%20(4).jar:?]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:313) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:272) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [flux.jar:FluxSpigot-04511af6]
28.07 22:49:12 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by Phoenix616** [comment] 2018-07-28 21:54
Duplicate of #95

**Closed by Phoenix616** 2018-07-28 21:54 UTC
Labels: duplicate
