### ISSUE TITLE
Aternos - Version 1.2.0 - Minecraft Version 1.12 - Paper Bukkit

### ISSUE THREAD

**Issue by nagnol** [novucs/factions-top#144] opened 2020-12-02 21:36 UTC
Hi! I didn't want to leave a review about a problem like everybody else, so I decided to take my issue here to see if you could help me out. I have this plugin as an option on Aternos and I tried to install it onto my factions server to use it, but when I try to do /f top, nothing happens. It shows as a red plugin instead of a green plugin like the rest. Is there any possible solutions for this? If you want to know, I could give you a list of my plugins if that is the problem.

**Comment by Phoenix616** [comment] 2020-12-02 21:46
Please provide your full log file. It should contain the error which is causing the plugin to stop as well as other useful information like the exact plugin and server version. (Also you might want to update to the latest [dev build](https://ci.minebench.de/job/FactionsTop/) to see if that fixes the issue already)

**Comment by nagnol** [comment] 2020-12-02 21:51
I appreciate the quick feedback. I'll attach a log file right now. https://pastebin.com/U4G8P9bu <--- Here it is.

**Comment by Phoenix616** [comment] 2020-12-02 21:59
That's a duplicate of #133 and should be fixed in the linked dev build. Please update to that.

**Closed by Phoenix616** 2020-12-02 21:59 UTC
Labels: missing information
