### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by storm0chaser** [novucs/factions-top#125] opened 2020-03-02 07:28 UTC
[12:53:21 INFO]: [FactionsTop] Enabling FactionsTop v1.2.0
[12:53:21 INFO]: [FactionsTop] Essentials found, using as economy backend.
[12:53:21 INFO]: [FactionsTop] Configuration file has been successfully updated.
[12:53:21 ERROR]: Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/zcore/persist/MemoryBoard
at net.novucs.ftop.hook.Factions0106.initialize(Factions0106.java:42) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_212]
at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:371) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:138) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:659) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1180) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:993) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:809) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:821) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:748) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:649) [StellarSpigot.jar:git-TacoSpigot-04511af6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.zcore.persist.MemoryBoard
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 26 more
[12:53:21 INFO]: [FactionsTop] Disabling FactionsTop v1.2.0
[12:53:21 INFO]: [PlaceholderAPI] Unregistered placeholder expansion: factionstop
[12:53:21 INFO]: [FactionsTop] Preparing shutdown...
[12:53:21 INFO]: [FactionsTop] Shutting down chunk worth task...
[12:53:21 INFO]: [FactionsTop] Saving everything to database...
[12:53:21 INFO]: [FactionsTop] Terminating plugin services...
[12:53:21 ERROR]: Error occurred while disabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NullPointerException
at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:177) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]

**Comment by Phoenix616** [comment] 2020-03-02 11:56
Duplicate of #124

**Closed by Phoenix616** 2020-03-02 11:56 UTC
