### ISSUE TITLE
Plugin won't load, not even in the latest build

### ISSUE THREAD

**Issue by promlgxd** [novucs/factions-top#135] opened 2020-04-09 10:28 UTC
Minecraft Version: 1.12.2
MassiveCore Version: 2.14.0
FactionsTop Version: Latest build from Jenkins. (1.2.1-SNAPSHOT)

The plugin just does not activate. I had an old version and after updating the problem is still there. What could be wrong?

[FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT
[18:43:07 INFO]: [FactionsTop] Essentials found, using as economy backend.
[18:43:07 ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
at net.novucs.ftop.shade.com.zaxxer.hikari.HikariConfig.(HikariConfig.java:50) ~[?:?]
at net.novucs.ftop.Settings.loadHikariConfig(Settings.java:442) ~[?:?]
at net.novucs.ftop.Settings.load(Settings.java:523) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:385) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
... 16 more

**Comment by Phoenix616** [comment] 2020-04-09 11:32
Duplicate of #133

**Closed** 2020-04-09 11:32 UTC
Labels: duplicate
